name: Run Postman Collection

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-collection:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # 3️⃣ Install dependencies
      - name: Install npm dependencies
        run: npm install

      # 4️⃣ Run Newman via npm script
      - name: Run Newman Collection with HTML report
        run: |
          npm run run:newman
          echo "Listing files in newman-report:"
          ls -la newman-report

      # 5️⃣ Verify HTML report
      - name: Verify HTML report exists
        run: |
          if [ ! -f newman-report/report.html ]; then
            echo "ERROR: Newman HTML report not found!"
            exit 1
          else
            echo "✅ Newman HTML report exists."

      # 6️⃣ Upload HTML report as artifact
      - name: Upload Newman HTML report
        uses: actions/upload-artifact@v3
        with:
          name: newman-html-report
          path: newman-report/report.html
