name: Run Postman Collection with HTML Report

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-collection:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Run Newman Collection using anthonyvscode/newman-action
      - name: Run Newman Collection (HTML report)
        uses: anthonyvscode/newman-action@v1
        with:
          collection: WorkingTestAPICollection.json
          reporters: html
          htmlReport: newman-report.html

      # 3️⃣ Upload HTML report as artifact
      - name: Upload Newman HTML report
        uses: actions/upload-artifact@v3
        with:
          name: newman-html-report
          path: newman-report.html
