name: Run Postman Collection (Mini)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-collection:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      # 3️⃣ Install Newman + HTML reporter globally
      - name: Install Newman and HTML reporter
        run: |
          npm install -g newman newman-reporter-html

      # 4️⃣ Run Newman with HTML report
      - name: Run Newman Collection
        run: |
          mkdir -p newman-report
          newman run WorkingTestAPICollection.json \
            --reporters cli,html \
            --reporter-html-export newman-report/report.html
          echo "Files in newman-report:"
          ls -la newman-report

      # 5️⃣ Upload HTML report as artifact
      - name: Upload Newman HTML report
        uses: actions/upload-artifact@v3
        with:
          name: newman-html-report
          path: newman-report/report.html
