name: Run Postman Collection

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-collection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Newman globally
        run: npm install -g newman

      - name: Run Postman Collection with HTML report
        run: |
          mkdir -p newman-report
          newman run WorkingTestAPICollection.json \
            --reporters cli,html \
            --reporter-html-export newman-report/report.html \
            --disable-unicode

      - name: Upload Newman HTML report
        uses: actions/upload-artifact@v3
        with:
          name: newman-html-report
          path: newman-report/report.html
